<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title><%showmedia.popuptext%></title>
<style type="text/css">
img { border: none; }
body { margin: 0px; }
</style>
</head><!-- image content -->
<body onblur="window.close()">
<%if.showmedia.popupdb%>
	<a href="javascript:window.close();"><%showmedia.imgdb%></a>
<%else%>
	<a href="javascript:window.close();"><%showmedia.img%></a>
<%endif%>
</body>
</html>